import React, { useState } from 'react';
import { useSOC } from '../../context/SOCContext';
import { MITRE_MATRIX_DATA } from '../../data/mockData';
import {
  Grid,
  Search,
  Filter,
  Flame,
  ShieldCheck,
  AlertTriangle,
  Download,
  Crosshair,
  ExternalLink,
  Layers,
  X,
} from 'lucide-react';
import { downloadMockFile } from '../../utils/cyberEffects';

export default function MitreMatrixModule() {
  const { addToast, setActiveModule } = useSOC();
  const [selectedTechnique, setSelectedTechnique] = useState(
    MITRE_MATRIX_DATA[1].techniques[0] // PowerShell
  );
  const [filterStatus, setFilterStatus] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');

  const handleExportMitreNavigator = () => {
    const navLayer = {
      name: 'JOCKY SOC Enterprise Coverage Layer',
      version: '4.5',
      domain: 'mitre-enterprise',
      description: 'Heuristic and behavioral detection heatmap generated by JOCKY Forensics Core',
      techniques: MITRE_MATRIX_DATA.flatMap((tactic) =>
        tactic.techniques.map((tech) => ({
          techniqueID: tech.id,
          tactic: tactic.name.toLowerCase().replace(/\s+/g, '-'),
          score: tech.hits,
          comment: `Rule: ${tech.rule} | Affected: ${tech.affected}`,
        }))
      ),
    };
    downloadMockFile('JOCKY_MITRE_ATTACK_Navigator_Layer.json', JSON.stringify(navLayer, null, 2));
    addToast('Navigator Exported', 'MITRE ATT&CK JSON layer generated and downloaded.', 'success');
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl glass-panel-glow border-cyan-500/30 bg-gradient-to-r from-slate-900/90 via-[#0b1022]/90 to-purple-950/40">
        <div>
          <div className="flex items-center gap-2">
            <Grid className="w-5 h-5 text-cyan-400" />
            <h1 className="text-xl font-bold font-cyber tracking-wide text-white">
              MITRE ATT&amp;CK MATRIX HEATMAP (10 TACTICS)
            </h1>
          </div>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Real-time adversary technique correlation across all 10 core Enterprise kill chain tactics
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleExportMitreNavigator}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-purple-950/80 hover:bg-purple-900 text-purple-300 border border-purple-500/40 text-xs font-mono transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            Export ATT&amp;CK Navigator
          </button>
        </div>
      </div>

      {/* Filter and Legend Bar */}
      <div className="p-3.5 rounded-xl glass-panel border-cyan-500/20 flex flex-col md:flex-row items-center justify-between gap-3 text-xs font-mono">
        {/* Heatmap Legend */}
        <div className="flex items-center gap-3 flex-wrap">
          <span className="text-slate-400 font-semibold">Heatmap Legend:</span>
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-3 rounded bg-red-600 shadow-[0_0_8px_#ef4444]" />
            <span className="text-slate-200">Observed Attack (Active P1)</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-3 rounded bg-amber-500" />
            <span className="text-slate-200">Detected / Guarded</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-3 rounded bg-cyan-600" />
            <span className="text-slate-200">Monitored Sensor</span>
          </div>
        </div>

        {/* Search */}
        <div className="relative w-full md:w-64">
          <Search className="w-3.5 h-3.5 text-cyan-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search technique name or ID..."
            className="w-full bg-slate-900/80 rounded-xl pl-8 pr-3 py-1.5 text-xs font-mono text-white placeholder-slate-500 border border-slate-700/60 focus:outline-none focus:border-cyan-400"
          />
        </div>
      </div>

      {/* 10-Tactic Interactive Matrix Grid (Horizontal Scrollable) */}
      <div className="rounded-2xl glass-panel border-cyan-500/20 overflow-x-auto p-4">
        <div className="min-w-[1200px] grid grid-cols-10 gap-3">
          {MITRE_MATRIX_DATA.map((tactic) => (
            <div key={tactic.tacticId} className="flex flex-col space-y-2">
              {/* Tactic Column Header */}
              <div className="p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-center">
                <div className="text-[10px] text-cyan-400 font-mono font-bold">{tactic.tacticId}</div>
                <div className="text-xs font-bold text-white font-cyber tracking-tight line-clamp-1 mt-0.5">
                  {tactic.name}
                </div>
                <div className="text-[10px] text-slate-500 font-mono mt-0.5">
                  {tactic.techniques.length} Techniques
                </div>
              </div>

              {/* Techniques Cards */}
              <div className="space-y-2 flex-1">
                {tactic.techniques.map((tech) => {
                  const isSelected = selectedTechnique?.id === tech.id;
                  const isObserved = tech.status === 'Observed';
                  const isDetected = tech.status === 'Detected';

                  const matchesSearch =
                    !searchQuery ||
                    tech.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                    tech.id.toLowerCase().includes(searchQuery.toLowerCase());

                  if (!matchesSearch) return null;

                  return (
                    <button
                      key={tech.id}
                      onClick={() => setSelectedTechnique(tech)}
                      className={`w-full p-2.5 rounded-xl text-left border transition-all text-xs font-mono relative group ${
                        isSelected
                          ? 'ring-2 ring-cyan-400 bg-slate-800 border-cyan-400'
                          : isObserved
                          ? 'bg-red-950/40 border-red-500/50 hover:border-red-400 shadow-[0_0_10px_rgba(239,68,68,0.2)]'
                          : isDetected
                          ? 'bg-amber-950/30 border-amber-500/40 hover:border-amber-400'
                          : 'bg-slate-900/60 border-slate-800 hover:border-slate-700'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-[10px] text-slate-400 font-bold">{tech.id}</span>
                        <span
                          className={`text-[9px] px-1.5 py-0.2 rounded font-bold ${
                            isObserved
                              ? 'bg-red-600 text-white animate-pulse'
                              : isDetected
                              ? 'bg-amber-500 text-black'
                              : 'bg-cyan-950 text-cyan-300'
                          }`}
                        >
                          {tech.hits} Hits
                        </span>
                      </div>
                      <div className="font-bold text-white text-[11px] leading-snug line-clamp-2">
                        {tech.name}
                      </div>
                      <div className="text-[9px] text-slate-400 mt-1 truncate">
                        {tech.rule}
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Selected Technique Inspector Drawer */}
      {selectedTechnique && (
        <div className="p-5 rounded-2xl glass-panel-glow border-purple-500/30 flex flex-col md:flex-row items-start justify-between gap-4">
          <div className="space-y-2 flex-1">
            <div className="flex items-center gap-2.5">
              <span className="px-2.5 py-1 rounded bg-purple-950 text-purple-300 border border-purple-500/40 font-mono font-bold text-xs">
                {selectedTechnique.id}
              </span>
              <h2 className="text-base font-bold font-cyber text-white">
                {selectedTechnique.name}
              </h2>
              <span
                className={`text-[10px] px-2 py-0.5 rounded font-mono font-bold uppercase ${
                  selectedTechnique.status === 'Observed'
                    ? 'bg-red-950 text-red-300 border border-red-500/40'
                    : 'bg-amber-950 text-amber-300 border border-amber-500/40'
                }`}
              >
                {selectedTechnique.status}
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-2 text-xs font-mono text-slate-300">
              <div className="p-2.5 rounded-xl bg-slate-900/80 border border-slate-800">
                <span className="text-slate-400 block text-[10px]">Detection Rule:</span>
                <strong className="text-cyan-300">{selectedTechnique.rule}</strong>
              </div>
              <div className="p-2.5 rounded-xl bg-slate-900/80 border border-slate-800">
                <span className="text-slate-400 block text-[10px]">Affected Fleet Systems:</span>
                <strong className="text-white">{selectedTechnique.affected}</strong>
              </div>
              <div className="p-2.5 rounded-xl bg-slate-900/80 border border-slate-800">
                <span className="text-slate-400 block text-[10px]">Total Detections:</span>
                <strong className="text-red-400">{selectedTechnique.hits} Correlated Events</strong>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={() => {
                setActiveModule('hunting');
                addToast('Threat Hunting', `Pivoting to search rules for ${selectedTechnique.name}`, 'info');
              }}
              className="px-3.5 py-2 rounded-xl bg-cyan-950 hover:bg-cyan-900 text-cyan-300 border border-cyan-500/40 text-xs font-mono font-semibold transition-colors flex items-center gap-1.5"
            >
              <Crosshair className="w-3.5 h-3.5" />
              Hunt for Technique
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
